[build]
  command = "npm run build"
  publish = "dist"

[server]
  headers = { "Cache-Control" = "public, max-age=0, must-revalidate" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
